name: Build and Test Dockerized Shiny

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t forest_fire_shiny_app:latest .

    # Step 4: Run the container for testing
    - name: Run Docker Container
      run: |
        docker run -d -p 3838:3838 --name forest_fire_shiny_app forest_fire_shiny_app:latest
        sleep 10  # Wait for the app to start

    # Step 5: Test the app
    - name: Test Shiny App
      run: |
        curl --fail http://localhost:3838 || (echo "App is not running" && exit 1)

    # Step 6: Stop and remove the container
    - name: Cleanup
      run: |
        docker stop forest_fire_shiny_app
        docker rm forest_fire_shiny_app
